services:
  n8n:
    build: .
    restart: unless-stopped
    volumes:
      - n8n_data:/home/node/.n8n
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10
volumes:
  n8n_data:
    external: true
    name: ngwog0o0c48owgoc4okokggw_n8n-data
